services:
  - type: web
    name: docmind-backend
    runtime: python
    rootDir: backend
    buildCommand: bash build.sh
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
      - key: JWT_EXPIRE_MINUTES
        value: "60"
      - key: TESSERACT_CMD
        value: tesseract
      - key: ALLOWED_ORIGINS
        sync: false
    buildFilter:
      paths:
        - backend/**
